# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.23-alpine AS builder
WORKDIR /app

# Install git for module fetching
RUN apk add --no-cache git sed

# Copy go modules and fix go version
COPY go.mod go.sum ./
RUN sed -i 's/go 1\.23\.4/go 1.23/' go.mod
RUN go mod download

# Copy source code
COPY . .

# Build the binary
RUN go build -o annas-mcp ./cmd/annas-mcp

# Final image
FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /usr/local/bin
COPY --from=builder /app/annas-mcp .
ENTRYPOINT ["/usr/local/bin/annas-mcp"]
CMD ["mcp"]
